### ISSUE TITLE
Add instruction for setting up the extension on the README

### ISSUE THREAD

**Issue by akshatnitd** [NJACKWinterOfCode/Tabs-Share#6]
**Actual Behaviour**
* No info present on the README

**Expected Behaviour**
* Add instruction for setting up the extension on the README

**Comment by rkishan516** [comment]
I am working on this. Can i ?

**Comment by samagragupta** [comment]
@rkishan516 If you are not working on this, then can I work on this.

**Comment by rkishan516** [comment]
@samagragupta I have already sent a PR regarding this but not accepted Yet. I have fully complete this.

**Comment by rkishan516** [comment]
@akshatnitd Please Look at It.

**Comment by akshatnitd** [comment]
Check my review @rkishan516

**Comment by rkishan516** [comment]
@akshatnitd Now Please Look at it
